### ISSUE TITLE
Difference in NextClade/Pangolin Assignments between viralrecon and the official web apps

### ISSUE THREAD

**Issue by stevin-wilson** [nf-core/viralrecon#241] opened 2021-12-19 15:38 UTC
# nf-core/viralrecon bug report

Hi

I am part of a SARS-CoV-2 surveillance team, and we have been using nf-core/viralrecon extensively in our project [Thank you :) ]. Recently, we have been having several omicron variant samples (we have been using a wet lab assay to predict the variant associated with samples prior to sequencing), and we are noticing that viralrecon calls them as 20A or 20B. I uploaded the consensus sequence files from `results/variant/ivar/consensus` into [NextClade](https://clades.nextstrain.org/) and  [Pangolin](https://pangolin.cog-uk.io/) web apps, and the sequences are classified as 21K and B.1.1.529. I was wondering about the cause of this discrepancy.

## Check Documentation

I have checked the following places for your error:

- [ X] [nf-core website: troubleshooting](https://nf-co.re/usage/troubleshooting)
- [ X] [nf-core/viralrecon pipeline documentation](https://nf-co.re/viralrecon/usage)

## Steps to reproduce

Steps to reproduce the behaviour:

1. Command line: 

nextflow run nf-core/viralrecon \
    --input samplesheet.csv \
    --platform illumina \
    --protocol amplicon \
    --genome 'MN908947.3' \
    --primer_set artic \
    --primer_set_version 3 \
    --skip_assembly \
    -profile singularity

## Log files

Have you provided the following extra information/files:

- [ X] The command used to run the pipeline
- [ ] The `.nextflow.log` file 

## System

- Hardware: HPC
- Executor: PBS
- OS: CentOS Linux
- Version 8.4.2105

## Nextflow Installation

- Version: 21.10.3

## Container engine

- Engine: Singularity
- version: 3.8.0-1.el8

## Additional context

Attached is the pipeline report.

[pipeline_report.txt](https://github.com/nf-core/viralrecon/files/7741055/pipeline_report.txt)

Thank you

**Comment by stevin-wilson** [comment] 2021-12-19 15:40
A sample sequence that was identified as B.1.1 by viralrecon , and 21K/ B.1.1.529 by Nextclade/Pangolin

[omicron_sequence.txt](https://github.com/nf-core/viralrecon/files/7741071/omicron_sequence.txt)

**Comment by drpatelh** [comment] 2021-12-21 10:27
hI @stevin-wilson ! The simplest explanation is that the version of Nextclade / Pangolin used in the pipeline are older than the ones use in their respective online apps. I haven't had any time to come back and update the containers but you should be able to do this manually. I wrote some docs using Pangolin as an example [here](https://nf-co.re/viralrecon/2.2/usage#updating-containers). 

Using something like the below in a custom config should work for Pangolin.

```
process {
      withName: PANGOLIN {
          container = 'https://depot.galaxyproject.org/singularity/pangolin:3.1.17--pyhdfd78af_1'
      }
}
```

We have an open issue to bump the version of Nextclade as this may not be as straightforward since they changed the CLI options after the last release of this pipeline. Maybe @marcmtk has attempted to do this already and can help here?

In any case, please do come and find us on the #viralrecon channel on the [nf-core Slack workspace](https://nf-co.re/join) for more real-time help.

**Comment by marcmtk** [comment] 2021-12-21 14:14
My progress on the nextclade issue can be seen at https://github.com/marcmtk/modules/tree/new_nextclade/modules/nextcladenew. 
In short i've implemented the dataset command and moving on the the run command. 

When the run command is implemented, some small changes to the viralrecon code may be necessary to get the most out of the nextclade output.

For pangolin we're currently using the solution shown by @drpatelh.

**Comment by drpatelh** [comment] 2022-01-07 18:06
Semi-duplicate of https://github.com/nf-core/viralrecon/issues/235

Pangolin version has been bumped in https://github.com/nf-core/viralrecon/pull/243/commits/81724748249b2971e500586903b4950a416fe648 and will be in the v2.3 release.

**Closed by drpatelh** 2022-01-07 18:06 UTC
Labels: enhancement, question
