### ISSUE TITLE
Add support for MGI's Atoplex kit

### ISSUE THREAD

**Issue by ljmesi** [nf-core/viralrecon#332] opened 2022-10-11 15:33 UTC
### Description of feature

Sequencing reads from MGI's Atoplex library prep kit is not currently supported. This feature adds support for it.

**Comment by drpatelh** [comment] 2023-03-05 09:23
Hi @ljmesi ! Be great to have some more info about this. Are there any links you could share for where we can find the primer sequences, ideally in BED format for this kit? Is it used for SARS-CoV-2? If you have used this kit with the pipeline already and have the files handy that would be even better. We may need to check that the vendor permits public distribution of their primer sites too because this isn't always the case.

**Comment by drpatelh** [comment] 2023-03-05 09:43
Duplicate of https://github.com/nf-core/viralrecon/issues/353

**Closed as completed** 2023-03-12 19:13 UTC
Labels: enhancement
