### ISSUE TITLE
IVar error with conda

### ISSUE THREAD

**Issue by Merguerrero** [nf-core/viralrecon#228] opened 2021-07-28 08:55 UTC
## Check Documentation

I have checked the following places for your error:

- [X] [nf-core website: troubleshooting](https://nf-co.re/usage/troubleshooting)
- [X] [nf-core/viralrecon pipeline documentation](https://nf-co.re/nf-core/viralrecon/usage)

## Description of the bug

Error while running IVAR_CONSENSUS or IVAR_VARIANTS with Conda .

## Steps to reproduce

Steps to reproduce the behaviour:

1. Command line:
 
nextflow run nf-core/viralrecon \
    --input samplesheet.csv \
    --platform illumina \
    --protocol amplicon \
    --genome 'MN908947.3' \
    --primer_set artic \
    --primer_set_version 3 \
    --skip_assembly \
    --max_cpus 4 \
    --max_memory '15.GB'\
    -profile conda
2. See error: 

 samtools: relocation error: viralrecon/work/conda/env-b6deb684c62494fb6921b1962c660b51/bin/../lib/./libssl.so.1.1: symbol EVP_idea_cbc version OPENSSL_1_1_0 not defined in file libcrypto.so.1.1 with link time reference

## Log files

Have you provided the following extra information/files:

- [X] The command used to run the pipeline
- [X] The `.nextflow.log` file 

[nextflow.log](https://github.com/nf-core/viralrecon/files/6891631/nextflow.log)

## System

- Hardware:  Desktop
- Executor:  local
- OS:  Debian 
- Version  10.10

## Nextflow Installation

- Version:  21.04.3

## Container engine

- Engine:  Conda 
- version:  4.10.3
- Image tag:  nf-core/viralrecon v2.1

**Comment by drpatelh** [comment] 2021-07-28 14:02
Hi @Merguerrero ! Hope you are well! If possible, I would strongly advise using either Singularity / Docker with the pipeline because there will be issues having to install multiple Conda environments required by the pipeline and it isn't reproducible. Unfortunately, there isn't a way around this if we want to write the pipeline in a modular fashion. Will close this for now because it is a known issue but for real-time help please come and find us in the #viralrecon channel on the [nf-core Slack Workspace](https://nf-co.re/join)

**Closed by drpatelh** 2021-07-28 14:02 UTC
Labels: question
