### ISSUE TITLE
Errors caused by R-version conflicts

### ISSUE THREAD

**Issue by jonbra** [nf-core/viralrecon#161] opened 2021-03-15 15:14 UTC
Hi,
There seems to be some conflicts with the version of R and some packages, maybe only the package `scales`. The entire pipeline ran smoothly with the test data, but on my own data this error arose:

```
Mar-15 14:07:32.450 [Task monitor] ERROR nextflow.processor.TaskProcessor - Error executing process > 'MOSDEPT
H_AMPLICON_PLOT'

Caused by:
  Process `MOSDEPTH_AMPLICON_PLOT` terminated with an error exit status (1)

Command executed:

  plot_mosdepth_regions.r \
      --input_files SWIFT25213950.trim.mkD.amplicon.regions.bed.gz \
      --input_suffix .trim.mkD.amplicon.regions.bed.gz \
      --output_dir ./ \
      --output_suffix .trim.mkD.amplicon.regions

Command exit status:
  1

Command output:
  (empty)

Command error:
  package ‘scales’ was built under R version 3.6.3 
  Loading required package: grid
  ========================================
  ComplexHeatmap version 2.2.0
  Bioconductor page: http://bioconductor.org/packages/ComplexHeatmap/
  Github page: https://github.com/jokergoo/ComplexHeatmap
  Documentation: http://jokergoo.github.io/ComplexHeatmap-reference
  
  If you use it in published research, please cite:
  Gu, Z. Complex heatmaps reveal patterns and correlations in multidimensional 
    genomic data. Bioinformatics 2016.
  ========================================
  
  Loading required package: viridisLite
  
  Loading required package: viridisLite
  
  Attaching package: ‘viridis’
  
  The following object is masked from ‘package:scales’:
  
      viridis_pal
  
  Warning messages:
  1: package ‘viridis’ was built under R version 3.6.3 
  2: package ‘viridisLite’ was built under R version 3.6.3 
  ── Attaching packages ─────────────────────────────────────── tidyverse 1.3.0 ──
  ✔ tibble  3.0.1     ✔ dplyr   1.0.0
  ✔ tidyr   1.1.0     ✔ stringr 1.4.0
  ✔ readr   1.3.1     ✔ forcats 0.5.0
  ✔ purrr   0.3.4     
  ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
  ✖ readr::col_factor() masks scales::col_factor()
  ✖ purrr::discard()    masks scales::discard()
  ✖ dplyr::filter()     masks stats::filter()
  ✖ dplyr::lag()        masks stats::lag()
  Warning messages:
  1: package ‘tidyverse’ was built under R version 3.6.3 
  2: package ‘tibble’ was built under R version 3.6.3 
  3: package ‘tidyr’ was built under R version 3.6.3 
  4: package ‘readr’ was built under R version 3.6.3 
  5: package ‘purrr’ was built under R version 3.6.3 
  6: package ‘dplyr’ was built under R version 3.6.3 
  7: package ‘stringr’ was built under R version 3.6.3 
  8: package ‘forcats’ was built under R version 3.6.3 
  Error:   Dimensions exceed 50 inches (height and width are specified in 'cm' not pixels).
    If you're sure you want a plot that big, use `limitsize = FALSE`.
  Backtrace:
      █
   1. └─ggplot2::ggsave(...)
   2.   └─ggplot2:::plot_dim(...)
  Execution halted
```

**Comment by drpatelh** [comment] 2021-04-27 12:57
Apologies for the late response @jonbra ! Did you manage to get to the bottom of this?

**Comment by drpatelh** [comment] 2021-04-27 12:59
We have been threatening to release v2.0 for a while now but hopefully soon 🤞🏽 If you haven't already be great if you can test with 

```console
nextflow pull nf-core/viralrecon
nextflow run nf-core/viralrecon ......... -r dev
```

**Comment by drpatelh** [comment] 2021-05-10 19:44
Will close this for now but feel free to re-open if the issue persists in the upcoming release @jonbra 👍🏽

**Closed by drpatelh** 2021-05-10 19:44 UTC
Labels: question

**Comment by asanenjoy** [comment] 2024-03-24 19:35
Hello sorry to re-open this. Have encountered the similar issue. Please see the error message below - 

ERROR ~ Error executing process > 'NFCORE_VIRALRECON:ILLUMINA:PLOT_MOSDEPTH_REGIONS_AMPLICON'

Caused by:
  Process `NFCORE_VIRALRECON:ILLUMINA:PLOT_MOSDEPTH_REGIONS_AMPLICON` terminated with an error exit status (1)

Command executed:

  plot_mosdepth_regions.r \
      --input_files cGMPSARS-CoV-2.regions.bed.gz \
      --output_dir ./ \
      --output_suffix mosdepth \
      --input_suffix .regions.bed.gz

  cat <<-END_VERSIONS > versions.yml
  "NFCORE_VIRALRECON:ILLUMINA:PLOT_MOSDEPTH_REGIONS_AMPLICON":
      r-base: $(echo $(R --version 2>&1) | sed 's/^.*R version //; s/ .*$//')
  END_VERSIONS

Command exit status:
  1

Command output:
  (empty)

Command error:
  Warning message:
  package ‘optparse’ was built under R version 4.0.5
  Warning message:
  package ‘scales’ was built under R version 4.0.5
  Loading required package: grid
  Error: package or namespace load failed for ‘ComplexHeatmap’:
   .onLoad failed in loadNamespace() for 'Cairo', details:
    call: dyn.load(file, DLLpath = DLLpath, ...)
    error: unable to load shared object '/root/work/conda/env-05a634cd6ec064941b9d92badb58aa6c/lib/R/library/Cairo/libs/Cairo.so':
    libicuuc.so.70: cannot open shared object file: No such file or directory
  Execution halted

Have updated my r-base in conda-forge, which is 4.3.3 instead of 4.0.5. Attempted with the following command - 

conda install -c conda-forge r-base=4.0.5

That didn't work though... 

Any input would be much appreciated! Thank you!
