### ISSUE TITLE
Data download from ENA/SRA before the main pipeline execution

### ISSUE THREAD

**Issue by jpflorido** [nf-core/viralrecon#101] opened 2020-05-18 14:35 UTC
Hi!
I'm running viralrecon pipeline for a dataset that has to be downloaded from ENA/SRA before the pipeline runs, but it fails. 
This is the error:

![image](https://user-images.githubusercontent.com/5921257/82224932-c74ff580-9924-11ea-81d2-a4a17366beb6.png)

This is the command:
```bash
nextflow run nf-core/viralrecon -r dev --input <path_to>/SRR11140744_metagenomic_sample_sheet.csv --fasta <path_to>/GCF_009858895.2_ASM985889v3_genomic.200409.fna.gz --gff <path_to>/GCF_009858895.2_ASM985889v3_genomic.200409.gff.gz -profile singularity --outdir <path_to_outputdir>   --max_cpus 5 --max_memory '16.GB'
```

And this is the sample sheet:
```bash
sample,fastq_1,fastq_2
SRR11140744,,
```

It seems that the command
`md5sum -c SRX7777166_T1_1.fastq.gz.md5`
is not working, since there is nothing to check.

Thanks,
Javier

**Comment by drpatelh** [comment] 2020-05-19 21:03
Hi @jpflorido! Sorry, I completely missed this :)

I have tried to run the pipeline with the same samplesheet you sent and it runs through fine. Could be a issue fetching the runinfo for the sample which is a bit odd.

Can you try and remove your local version of the pipeline and try again please?

`rm -r ~/.nextflow/assets/nf-core/viralrecon/`

**Comment by drpatelh** [comment] 2020-05-20 11:30
Closing for now @jpflorido because I wasnt able to reproduce the problem. Please feel free to re-open or join the #viralrecon channel on the [nf-core Slack workspace](https://nf-co.re/join) if you have any more issues.

**Closed by drpatelh** 2020-05-20 11:30 UTC
