### ISSUE TITLE
IVAR_VARIANTS silently failing when FAI index is missing

### ISSUE THREAD

**Issue by rarthur-eicc** [nf-core/viralrecon#286] opened 2022-02-21 17:06 UTC
### Description of the bug

Hi, 

I've had an issue on 2 of 3 new sequencing batches my group has analyzed of sars cov2 data since the 2.3/2.3.1 viralrecon updates. A quick note is that I run each batch in two different versions of viralrecon, one with the parameter --ivar_trim_offset 5 as recommended for Swift amplicons, and one without. I am the person who wrote in on slack a few months back about getting the correct Swift primers, and I have successfully analyzed dozens of batches of data. My PI and other colleagues have asked me to run with and without this parameter as omicron samples have known issues with it and the Swift primers (we've spoken with Swift). I mention this in case you notice the lack of that parameter in my supplied command to invoke viralrecon.

Anyway, the main issue is that I am getting an error in 2 new batches with 2 unrelated samples that have passed QC checks etc. ViralRecon will complete all steps up to bcftools consensus and will spit out the error below. It then fails to proceed forward with the multiqc stages, etc. 

Interestingly, for this particular sample, viralrecon DID successfully complete with the ivar_trim_offset 5 parameter on, but failed without it. I have updated to the latest nextflow and viralrecon versions. I have included my slightly tweaked multiqc config file  as a .txt since you cannot upload .yaml ( I need more info from mosdepth, this adds that into the report ) and my pangolin config. Prior to v2.3, I was manually providing updated pangolin paths per the suggestion on the viralrecon docs as we want the latest pangolin DB.

If I remove the problematic sample and run viralrecon only just on it, it magically works with the same parameters. So, I have to wait a few hours to process my entire sequencing run, find out that bcftools crashed with the error shown, and then isolate the sample and re-run it alone, and then re-run the entire rest of the batch.

Is there a way to resolve this issue with the bcftools consensus command? We did not see this sort of issue with viralrecon 2.2 as it is with the bcftools consensus portion of the pipeline.

Thank you in advance,
Robert Arthur

### Command used and terminal output

```console
The main analysis portion command issued:
nextflow run nf-core/viralrecon -profile docker --input samplesheet.csv --platform illumina --protocol amplicon --genome 'MN908947.3' --primer_bed swift_refv3_primers.bed --skip_assembly --skip_kraken2 --multiqc_config '/home/rarthur/new_multiqc_config.yaml' --email_on_fail 'rarthu3@emory.edu' -c pangolin_config.txt 


Error:
-[nf-core/viralrecon] Pipeline completed with errors-
WARN: To render the execution DAG in the required format it is required to install Graphviz -- See http://www.graphviz.org for more info.
Error executing process > 'NFCORE_VIRALRECON:ILLUMINA:CONSENSUS_BCFTOOLS:BCFTOOLS_CONSENSUS (EHC_C19_3957E_S8_L001)'

Caused by:
  Process `NFCORE_VIRALRECON:ILLUMINA:CONSENSUS_BCFTOOLS:BCFTOOLS_CONSENSUS (EHC_C19_3957E_S8_L001)` terminated with an error exit status (255)

Command executed:

  cat EHC_C19_3957E_S8_L001.masked.fa \
      | bcftools \
          consensus \
          EHC_C19_3957E_S8_L001.filtered.vcf.gz \
           \
          > EHC_C19_3957E_S8_L001.fa
  
  cat <<-END_VERSIONS > versions.yml
  "NFCORE_VIRALRECON:ILLUMINA:CONSENSUS_BCFTOOLS:BCFTOOLS_CONSENSUS":
      bcftools: $(bcftools --version 2>&1 | head -n1 | sed 's/^.*bcftools //; s/ .*$//')
  END_VERSIONS

Command exit status:
  255

Command output:
  (empty)

Command error:
  Note: the --sample option not given, applying all records regardless of the genotype
  The fasta sequence does not match the REF allele at MN908947.3:11282:
     REF .vcf: [ANNNNNNNNN]
     ALT .vcf: [A]
     REF .fa : [AGTTTGTCTG]GTTTTAAGCTAAAAGACTGTGTTATGTATGCATCAGCTGTAGTGTTACTAATCCTTATGACAGCAAGAA

Work dir:
  /mnt/beegfs/v1/eicc/home/rarthur/projects/viral/viralrecon/ehc_c19_ampseqs/feb172022_notrimoffset/work/f4/ee6d763427f4992701500c505bdd52

Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`
```

### Relevant files

[new_multiqc_config.txt](https://github.com/nf-core/viralrecon/files/8111011/new_multiqc_config.txt)
[pangolin_config.txt](https://github.com/nf-core/viralrecon/files/8111013/pangolin_config.txt)

### System information

Nextflow v 21.10.6
Viralrecon v2.3.1

**Comment by drpatelh** [comment] 2022-02-21 17:55
Hi @rarthur-eicc ! Hope you are well and thanks for reporting this!

Would it be possible to share the `.nextflow.log` generated by the pipeline as well as the contents of `-c pangolin_config.txt`? @saramonzon noticed that you are providing `--consensus_caller ivar` but the pipeline is still running `--consensus_caller bcftools` instead? This shouldn't be the case.

Are you able to try running the `dev` version because this may have been fixed already:

```
nextflow pull nf-core/viralrecon
nextflow run nf-core/viralrecon <YOUR_PARAMETERS> -r dev
```

Also, make sure you provide any custom parameters via `-params-file` rather than `-c` as I highlight in [this issue](https://github.com/nf-core/viralrecon/issues/283#issuecomment-1046237471) as this will impact they way the parameters are passed to the pipeline.

Thanks!

**Comment by rarthur-eicc** [comment] 2022-02-21 18:04
Hi Harshil,

Whoops! I copied the command from a test script I was using to see if forcing use of the ivar consensus caller would fix this. I've since edited that part. Sorry. 

The pangolin config .txt is attached above, but it's just:
  process {
      withName: PANGOLIN {
          container = 'quay.io/biocontainers/pangolin:3.1.20--pyhdfd78af_0'
      }
  }

As in one of your old posts about versioning. I am actually only running the pipeline as part of a larger pipeline within a SLURM job submitted via a large shell script with custom reports and other things, so I am curious if this is still acceptable ( the -c pangolin_config.txt) rather than using a parameters file. Trying to cut down on the number of files /inputs i need to copy per job. 

I will try to attach the correct .nextflog.log , I've done a lot of testing in that same directory. I have had this happen in two batches, so my memory might be a little boggled at the moment.
[nextflow.log](https://github.com/nf-core/viralrecon/files/8111338/nextflow.log)

**Comment by drpatelh** [comment] 2022-02-21 18:29
No worries!

Yep, your usage of `-c pangolin_config.txt` is correct in this context 👍🏽 I think those versions come with that version of the container anyway but I see how that makes it easier.

> For the dev version, I am still running / testing other batches today, so I don't think I can at the moment.

Cool. Be awesome if you can test `dev` as soon as you can - even if it is just on the failing sample. Means we can fix this issue sooner rather than you having to wait for the next release.

If you haven't zapped the `work` directory for the failing run already would you mind sending me the contents of the following files please? You will need to tab-complete the path below:

`/mnt/beegfs/v1/eicc/home/rarthur/projects/viral/viralrecon/ehc_c19_ampseqs/feb172022_notrimoffset/work/05/f37dba` -> TAB COMPLETE

And send me the contents of `.command.log`, `.command.sh`, `.command.err` and `.command.out` please. Want to confirm whether it's the same issue @saramonzon noticed and we have now fixed on `dev`.

**Comment by rarthur-eicc** [comment] 2022-02-21 18:38
Hey Harshil,

Yeah, I had updated it to 3.1.19 back during viralrecon 2.2, so that's what I meant. I manually just check quay.io and will plan to update as we go forward just in case viralrecon hasn't had an update yet. No worries there :) 

I have found the work folder, f37dbadc3b86271a3da81f0062d18d, and attached everything here. It has its own .command* files; are those what you want? Due to filesizes and a bunch of files beginning with `.`, I've zipped it up and tried to attach that way.
[forHarshil.zip](https://github.com/nf-core/viralrecon/files/8111498/forHarshil.zip)

Please let me know if the files attached successfully. If not, I'll remove the `.` from the start and add them manually.

**Comment by rarthur-eicc** [comment] 2022-02-21 18:47
Just in case the prior upload didn't work for the files beginning with `.` , I've attached them here.
[changedNames.zip](https://github.com/nf-core/viralrecon/files/8111535/changedNames.zip)

**Comment by drpatelh** [comment] 2022-02-21 19:02
Right! As @saramonzon suspected (chatting on Slack) it appears like we have fixed this bug in `dev`. It basically comes about as a result of not staging the `fai` file when running the `IVAR_VARIANTS` process. I still have no idea why it is only just becoming an issue for numerous users but it should now be fixed. 

When you have confirmed `dev` works for you we will release the pipeline on the off chance that something else breaks for you.

```
$ head .command.err
[mpileup] 1 samples in 1 input files
[mpileup] Max depth set to maximum value (2147483647)
[E::faidx_adjust_position] The sequence "MN908947.3" was not found
[E::faidx_adjust_position] The sequence "MN908947.3" was not found
[E::faidx_adjust_position] The sequence "MN908947.3" was not found
[E::faidx_adjust_position] The sequence "MN908947.3" was not found

$ head .command.log
[mpileup] 1 samples in 1 input files
[mpileup] Max depth set to maximum value (2147483647)
[E::faidx_adjust_position] The sequence "MN908947.3" was not found
[E::faidx_adjust_position] The sequence "MN908947.3" was not found
[E::faidx_adjust_position] The sequence "MN908947.3" was not found
[E::faidx_adjust_position] The sequence "MN908947.3" was not found
```

**Comment by rarthur-eicc** [comment] 2022-02-21 19:04
Thanks, Harshil.

I've started one of my problematic batches as follows:
`nextflow run nf-core/viralrecon -profile docker --input samplesheet.csv --platform illumina --protocol amplicon --genome 'MN908947.3' --primer_bed swift_refv3_primers.bed --skip_assembly --skip_kraken2 --multiqc_config '/home/rarthur/new_multiqc_config.yaml' --email_on_fail 'rarthu3@emory.edu' -c pangolin_config.txt -r dev --outdir ./results`

It will likely take 2-2.5 hours, but I will let y'all know how it goes.

For what it's worth, I have also tested the problematic batches with forcing the ivar consensus, and as expected, there are no errors as we don't even call bcftools. 

I really appreciate you / Sara taking a look at this and helping me out! :)

**Comment by drpatelh** [comment] 2022-02-21 19:26
Thank you for testing so quickly! 🤞🏽 🥁

**Comment by rarthur-eicc** [comment] 2022-02-21 21:31
Hi Harshil,

The test run in `dev` worked just fine even with a previously problematic set of 2 samples. 

Just wanted you to be aware.

Thanks!

**Comment by drpatelh** [comment] 2022-02-21 22:58
Awesome! Thanks for letting us know. v2.4 will be released tomorrow 🚀

**Closed by drpatelh** 2022-02-21 22:58 UTC
Labels: bug

**Comment by rarthur-eicc** [comment] 2022-02-22 14:11
Harshil,

I have just pulled the new version and attempted to run a test batch of 3 samples with the following code:

`nextflow run nf-core/viralrecon -profile docker --input samplesheet.csv --platform illumina --protocol amplicon --genome 'MN908947.3' --primer_bed swift_refv3_primers.bed --ivar_trim_offset 5 --skip_assembly --skip_kraken2 --multiqc_config '/home/rarthur/new_multiqc_config.yaml' --email_on_fail 'rarthu3@emory.edu' -c pangolin_config.txt --outdir ./results`

And I get the error below to stderr:

`Project `nf-core/viralrecon` currently is sticked on revision: dev -- you need to specify explicitly a revision with the option `-r` to use it`

Ideas?

**Comment by drpatelh** [comment] 2022-02-22 14:21
You can try to remove the cached version and try again:

```
rm -r ~/.nextflow/assets/nf-core/viralrecon/
```

**Comment by rarthur-eicc** [comment] 2022-02-22 14:23
That seems to have done it. Sorry if that was a dumb question, I didn't know I needed to do that. It is now processing properly.

:)
